/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package D03_Table;

import com.microsoft.sqlserver.jdbc.SQLServerDataSource;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class QLKhoa extends javax.swing.JFrame {

    /**
     * Creates new form frmTable2
     */
    public QLKhoa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMaKhoa = new javax.swing.JTextField();
        txtTenKhoa = new javax.swing.JTextField();
        txtNgayThanhLap = new javax.swing.JTextField();
        txtMaTK = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblKhoa = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        btnLoad = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Mã khoa:");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setText("Tên khoa:");

        jLabel3.setText("Ngày thành lập: ");

        jLabel4.setText("Mã trưởng khoa:");

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        tblKhoa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã khoa", "Tên khoa", "Ngày thành lập", "Mã trưởng khoa"
            }
        ));
        tblKhoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhoaMouseClicked(evt);
            }
        });
        tblKhoa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblKhoaKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(tblKhoa);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("THÔNG TIN KHOA");

        btnLoad.setText("Load");
        btnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNgayThanhLap, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtMaTK)
                            .addComponent(txtMaKhoa, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTenKhoa, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(btnCapNhat)
                                .addGap(30, 30, 30)
                                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMaKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNgayThanhLap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnXoa)
                    .addComponent(btnCapNhat)
                    .addComponent(btnLoad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        SQLServerDataSource ds = new SQLServerDataSource();
        
        ds.setUser("sa");
        ds.setPassword("sa");
        ds.setServerName("HP-LAP\\HP_MSSQLSERVER");
        ds.setPortNumber(Integer.parseInt("1433")); //1433
        ds.setDatabaseName("QLGV7");
        
        try {
            Connection con = ds.getConnection();
            PreparedStatement pst = con.prepareStatement("INSERT INTO KHOA (MAKHOA, TENKHOA, NGTLAP, TRGKHOA) VALUES (?,?,?,?)");
            
            pst.setString(1, txtMaKhoa.getText());
            pst.setString(2, txtTenKhoa.getText());
            pst.setString(3, txtNgayThanhLap.getText());
            pst.setString(4, txtMaTK.getText());
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Đã thêm thành công.");
            
            con.close();
            loadData();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "LỖI:\n" + ex);
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed
        // TODO add your handling code here:
        loadData();
    }//GEN-LAST:event_btnLoadActionPerformed

    private void tblKhoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhoaMouseClicked
        selectedRow();
        
    }//GEN-LAST:event_tblKhoaMouseClicked

    private void selectedRow() {
        // TODO add your handling code here:
        //clearAll();
        
        DefaultTableModel recordTable = (DefaultTableModel)tblKhoa.getModel();
        int selectedRow = tblKhoa.getSelectedRow();
        
        txtMaKhoa.setText(recordTable.getValueAt(selectedRow, 0).toString());
        txtTenKhoa.setText(recordTable.getValueAt(selectedRow, 1).toString());
        txtNgayThanhLap.setText(recordTable.getValueAt(selectedRow, 2).toString());
        txtMaTK.setText(recordTable.getValueAt(selectedRow, 3).toString());
        
        //System.err.println(recordTable.getValueAt(selectedRow, 3));
        
    }

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        SQLServerDataSource ds = new SQLServerDataSource();
        
        ds.setUser("sa");
        ds.setPassword("sa");
        ds.setServerName("HP-LAP\\HP_MSSQLSERVER");
        ds.setPortNumber(Integer.parseInt("1433")); //1433
        ds.setDatabaseName("QLGV7");
        
        try {
            Connection con = ds.getConnection();
            PreparedStatement pst = con.prepareStatement("DELETE FROM KHOA WHERE MAKHOA=?");
            
            pst.setString(1, txtMaKhoa.getText());
            
            pst.execute();
            JOptionPane.showMessageDialog(null, "Đã xóa thành công.");
            
            con.close();
            clearAll();
            loadData();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "LỖI XÓA:\n" + ex);
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        // TODO add your handling code here:
        SQLServerDataSource ds = new SQLServerDataSource();
        
        ds.setUser("sa");
        ds.setPassword("sa");
        ds.setServerName("HP-LAP\\HP_MSSQLSERVER");
        ds.setPortNumber(Integer.parseInt("1433")); //1433
        ds.setDatabaseName("QLGV7");
        
        try {
            Connection con = ds.getConnection();
            PreparedStatement pst = con.prepareStatement("UPDATE KHOA "
                    + "SET TENKHOA=?, NGTLAP=?, TRGKHOA=? "
                    + "WHERE (MAKHOA=?)");
            
            pst.setString(1, txtTenKhoa.getText());
            pst.setString(2, txtNgayThanhLap.getText());
            pst.setString(3, txtMaTK.getText());
            pst.setString(4, txtMaKhoa.getText());
                        
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Đã cập nật thành công.");
            
            con.close();
            loadData();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "LỖI CẬP NHẬT:\n" + ex);
        }
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void tblKhoaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblKhoaKeyPressed
        // TODO add your handling code here:
        selectedRow();
    }//GEN-LAST:event_tblKhoaKeyPressed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        clearAll();
    }//GEN-LAST:event_jLabel1MouseClicked
    private void clearAll(){
        txtMaKhoa.setText("");
        txtTenKhoa.setText("");
        txtNgayThanhLap.setText("");
        txtMaTK.setText("");
    }
    
    private void loadData(){
        SQLServerDataSource ds = new SQLServerDataSource();
        
        ds.setUser("sa");
        ds.setPassword("sa");
        ds.setServerName("HP-LAP\\HP_MSSQLSERVER");
        ds.setPortNumber(Integer.parseInt("1433")); //1433
        ds.setDatabaseName("QLGV7");
        
        try {
            Connection con = ds.getConnection();
            
            Statement cstmt = con.createStatement();
            
            ResultSet rs = cstmt.executeQuery("Select * from KHOA");
            
            DefaultTableModel tbModel = (DefaultTableModel)tblKhoa.getModel();
            
            tbModel.setRowCount(0);
            while (rs.next()) {
                String maKhoa = rs.getString("MAKHOA");
                String tenKhoa = rs.getString("TENKHOA");
                String ngayTL = rs.getString("NGTLAP");
                String maTK = rs.getString("TRGKHOA");
                
                String data[] = {maKhoa, tenKhoa, ngayTL, maTK};
                
                tbModel.addRow(data);
            }
            con.close();
        } catch (SQLException ex) {
            
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLKhoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLKhoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLKhoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLKhoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLKhoa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnLoad;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblKhoa;
    private javax.swing.JTextField txtMaKhoa;
    private javax.swing.JTextField txtMaTK;
    private javax.swing.JTextField txtNgayThanhLap;
    private javax.swing.JTextField txtTenKhoa;
    // End of variables declaration//GEN-END:variables
}
